### ISSUE TITLE
Should mod cursor earlier

### ISSUE THREAD

**Issue by tom76kimo** [xiaody/react-touch-carousel#8]
Currently update cursor when user touching carousel. Which introduces an issue that if you put like video player inside the carousel, assume we have 7 cards, when you scroll from cursor 0 to cursor -1, touch the -1 video player to start play, it will be modCursor to 6 card with -1 video player playing.

I currently update cursor based on [this](https://github.com/xiaody/react-touch-carousel/blob/master/src/TouchCarousel.js#L81-L86) every time `onRest` to workaround.

**Comment by xiaody** [comment]
Interesting. I have not thought much about such interactive card cases.

The reason why we choose to do the "moding" at `touchstart` instead of `rest` is that if a user swipes multiple times fast enough, the carousel may not rest at all and the cursor goes out of range. That said, I think it won't hurt to do modings in `onRest`, if it resolves your problem.

**Comment by tom76kimo** [comment]
I agree, there should be a better way/chance to do moding

**Comment by tom76kimo** [comment]
And this is a great lib btw, good work!

**Comment by xiaody** [comment]
Glad it helps :)
